# Generated by Django 5.0.4 on 2024-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0002_parkingowner_alter_customuser_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='available_spots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='total_spots',
            field=models.IntegerField(null=True),
        ),
    ]
