# Generated by Django 5.0.4 on 2024-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0003_alter_parking_available_spots_alter_parking_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
